### ISSUE TITLE
Some levels crash the editor

### ISSUE THREAD

**Issue by SuperPinger** [Interrupt/delverengine#207]
The crash occurs upon saving and exiting the play mode. This applies mostly to example levels included in the game, the cause of the issue is unknown so far. 
Examples include: beerhall.dat; collision.dat; spikes.bin; quarry.bin; slimeking.dat; directionalspikes.bin and possibly others.

**Comment by joshuaskelly** [comment]
This appears to be happening because the deserialized level has a null `tileMaterials` field and results in an NRE. This might be an issue with older levels?

**Comment by PythooonUser** [comment]
Might be, yes. I think `tileMaterials` is mandatory? If not, there might be an issue with the JSON utils?

**Comment by PythooonUser** [comment]
Stack trace:

```
java.lang.NullPointerException: Cannot store to object array because "this.tileMaterials" is null
        at com.interrupt.dungeoneer.game.Level.preSaveCleanup(Level.java:3679)
        at com.interrupt.dungeoneer.game.Level.preSaveCleanup(Level.java:3686)
        at com.interrupt.dungeoneer.GameManager.tick(GameManager.java:88)
        at com.interrupt.dungeoneer.screens.GameScreen.render(GameScreen.java:73)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at com.interrupt.dungeoneer.editor.EditorApplication.render(EditorApplication.java:559)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```
