### ISSUE TITLE
Number Format Exception When Using Arrow Keys In Input Field

### ISSUE THREAD

**Issue by PythooonUser** [Interrupt/delverengine#285]
When using the arrow keys "up" and "down" in an input field that is used as a float, the following crash occurs:

```
Exception in thread "LWJGL Application" java.lang.NumberFormatException: For input string: "0,9"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at com.interrupt.dungeoneer.editor.ui.PropertiesMenu$5.keyDown(PropertiesMenu.java:331)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:46)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:183)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:148)
        at com.badlogic.gdx.scenes.scene2d.Stage.keyDown(Stage.java:412)
        at com.badlogic.gdx.InputMultiplexer.keyDown(InputMultiplexer.java:80)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:322)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by PythooonUser** [comment]
Call to `DecimalFormat.format` is not applying the pattern `##.##` (it uses my German locale I think nonetheless).

See `DelvEdit\src\com\interrupt\dungeoneer\editor\ui\PropertiesMenu.java::337`.
