### ISSUE TITLE
Overworld mod doesn't appear to be complete

### ISSUE THREAD

**Issue by NetherNarwhal** [Interrupt/delverengine#4]
First off, thanks for releasing this! I love playing around with these. It inspired me to buy the game (not on sale :( ) and I am really enjoying it so far.

Anyway, when trying to run the Overworld mod the game will crash with the following message.

`[DelverGenerator] Using theme dir generator/Outdoor/
[DelverOutdoors] Creating new Chunk
[DelverGameManager] Fatal error!
java.lang.NullPointerException
	at com.interrupt.dungeoneer.game.OverworldChunk.SpawnEntity(OverworldChunk.java:646)
	at com.interrupt.dungeoneer.game.OverworldChunk.SpawnEntities(OverworldChunk.java:677)
	at com.interrupt.dungeoneer.game.OverworldChunk.Init(OverworldChunk.java:164)
	at com.interrupt.dungeoneer.game.terrain.threading.OverworldGenerationThread.run(OverworldGenerationThread.java:45)
	at com.interrupt.dungeoneer.game.OverworldChunk.generateOnThisThread(OverworldChunk.java:88)
	at com.interrupt.dungeoneer.game.OverworldLevel.makeNewChunk(OverworldLevel.java:354)
	at com.interrupt.dungeoneer.game.OverworldLevel.MakeNewChunks(OverworldLevel.java:326)
	at com.interrupt.dungeoneer.game.OverworldLevel.UpdateChunks(OverworldLevel.java:343)
	at com.interrupt.dungeoneer.game.OverworldLevel.tick(OverworldLevel.java:186)
	at com.interrupt.dungeoneer.game.Game.tick(Game.java:530)
	at com.interrupt.dungeoneer.GameManager.tick(GameManager.java:113)
	at com.interrupt.dungeoneer.screens.GameScreen.render(GameScreen.java:73)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
[Delver] Could not find file in any mods: meshes/sky.obj
[Delver] Could not find file in any mods: sky.png
[Delver] Could not find file in any mods: meshes.png`

I copied over the 3 files mentioned above from the retail copy, but the SpawnEntity method is crashing because it can't create a bush entity. Other missing files will be listed as well (probably from within one of the bin files since they aren't listed in the dungeon.dat), such as meshes/plane.obj, textures/wood-ladder.png, etc. None of those files are in the asset folder either. I certainly may have done something wrong, it doesn't look like this mod can run without content from the retail version of the game.

Sidenote: The test level will play, but has a bunch of warnings about missing audio files (dragging the audio folder from retail in fixes that). Also, you may want to upgrade the Gradle wrapper. I looks like it is for a really old version of Gradle and I couldn't get running with Java 10 or 8 (using Gradle 47 got further with different warnings, but 50+ definitely didn't work because of project Gradle config). I gave up before trying Java 6 and dumped Gradle and Maven and included the dependencies manually to get things running.

**Comment by SHADOWELITE7** [comment]
sometimes when you go into the mod. You don't really see all the monsters and some parts of the world has large cracks where you can see the bottom of the map layout.
